config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :med_histories
  resources :notes
  resources :events
  resources :recurring_events
  resources :patients do
    resources :med_histories, only: %i[new create]
    resources :notes, only: %i[new create]
  end
  resources :doctors
  get '/chart', to: 'home#chart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
end

app/models/med_history.rb
class MedHistory < ApplicationRecord
  belongs_to :patient
  # serialize :c1
end

app/controllers/med_histories_controller.rb
class MedHistoriesController < ApplicationController
  before_action :find_patient
  before_action :set_med_history, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /med_histories
  # GET /med_histories.json
  def index
    @med_histories = MedHistory.all
    @user = current_user
  end

  # GET /med_histories/1
  # GET /med_histories/1.json
  def show; end

  # GET /med_histories/new
  def new
    @med_history = MedHistory.new
  end

  # GET /med_histories/1/edit
  def edit; end

  # POST /med_histories
  # POST /med_histories.json
  def create
    @med_history = @patient.med_histories.new(med_history_params)

    respond_to do |format|
      if @med_history.save
        # format.html { redirect_to @med_history, notice: 'Med history was successfully created.' }
        # byebug
        format.html { redirect_to edit_patient_path(@med_history.patient.id), notice: 'Med history was successfully created.' }

        format.json { render :show, status: :created, location: @med_history }
      else
        format.html { render :new }
        format.json { render json: @med_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /med_histories/1
  # PATCH/PUT /med_histories/1.json
  def update
    respond_to do |format|
      if @med_history.update(med_history_params)
        format.html { redirect_to @med_history, notice: 'Med history was successfully updated.' }
        format.json { render :show, status: :ok, location: @med_history }
      else
        format.html { render :edit }
        format.json { render json: @med_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /med_histories/1
  # DELETE /med_histories/1.json
  def destroy
    @med_history.destroy
    respond_to do |format|
      format.html { redirect_to med_histories_url, notice: 'Med history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_patient
    # /../../.......png
    # params[:format] png

    # /../../.... .1
    # params[:format] 1
    @patient = params[:format] ? Patient.find(params[:format]) : Patient.find(params[:patient_id])
    # @patient = Patient.find(params[:format])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_med_history
    @med_history = MedHistory.find(params[:id])
    # @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def med_history_params
    params.require(:med_history).permit(:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :q11, :q12,
                                        :t1, :t2, :t3, :t4, :t5, :t6, :t7, :t8,
                                        :t9, :t10, :t11, :t12, :t13, :t14, :t15, :t16,
                                        :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24,
                                        :t25, :t26, :t27, :t28, :t29, :t30, :t31, :t32,
                                        :patient_id)
  end
end

app/helpers/med_histories_helper.rb
module MedHistoriesHelper
end

app/views/med_histories/_form.html.erb
<%= simple_form_for([@patient, @patient.med_histories.build]) do |f| %>

<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="container">
  <%= render partial: 'chart', :locals => { :f => f } %>
</div>
<br>
<br>
<h1>Antecedentes Medicos</h1>

<div class="row card">

  <div class='input-field col s6'>
    <%=f.label :q1, "Problemas Cardiacos", class: ''%>
    <br>
    <%=f.input :q1, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', class: 'padl' %>
  </div>

  <div class='input-field col s6'>
    <%=f.label :q2, "Diabetes"%>
    <br>
    <%=f.input :q2, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q3, "Hepatitis"%>
    <br>
    <%=f.input :q3, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q4, "Presion Sanguinea Anormal"%>
    <br>
    <%=f.input :q4, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q5, "Asma"%>
    <br>
    <%=f.input :q5, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q6, "Asma"%>
    <br>
    <%=f.input :q6, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q7, "Anemia"%>
    <br>
    <%=f.input :q7, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q8, "Epilepsia"%>
    <br>
    <%=f.input :q8, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q9, "Embarazada"%>
    <br>
    <%=f.input :q9, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q10, "Esta tomando algun medicamento?"%>
    <br>
    <%=f.input :q10, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q11, "H.I.V"%>
    <br>
    <%=f.input :q11, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <div class='input-field col s6'>
    <%=f.label :q12, "Transplantado"%>
    <br>
    <%=f.input :q12, as: :boolean, label: false, checked_value: 'Yes', unchecked_value: 'No', wrapper_html: { class: 'm6 s12' }%>
  </div>
  <%= f.hidden_field :patient_id %>
</div>

<div class="form-actions">
  <%= f.button :submit, class:'waves-effect waves-light btn' %>
</div>
<% end %>

app/views/med_histories/edit.html.erb
<div class="container">
  <h1>Medical History</h1>
  <br>
  <%= render 'form', med_history: @med_history %>
  <br>
  <!-- <%= link_to 'Show', @med_history, class: 'waves-effect waves-light btn' %> -->
  <br>
  <%= link_to 'Back', med_histories_path, class: 'waves-effect waves-light btn'%>
</div>

app/views/med_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical History</h1>

<table>
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th>Q8</th>
      <th>Q9</th>
      <th>Q10</th>
      <th>Q11</th>
      <th>Q12</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @med_histories.each do |med_history| %>
      <tr>
        <td><%= med_history.q1 %></td>
        <td><%= med_history.q2 %></td>
        <td><%= med_history.q3 %></td>
        <td><%= med_history.q4 %></td>
        <td><%= med_history.q5 %></td>
        <td><%= med_history.q6 %></td>
        <td><%= med_history.q7 %></td>
        <td><%= med_history.q8 %></td>
        <td><%= med_history.q9 %></td>
        <td><%= med_history.q10 %></td>
        <td><%= med_history.q11 %></td>
        <td><%= med_history.q12 %></td>
        <td><%= med_history.patient %></td>
        <td><%= link_to 'Show', med_history %></td>
        <td><%= link_to 'Edit', edit_med_history_path(med_history) %></td>
        <td><%= link_to 'Destroy', med_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Med History', new_med_history_path %>

app/views/med_histories/new.html.erb
<div class="container">
  <h4>Medical History</h4>
  <br>
  <%= render 'form', med_history: @med_history %>
  <br>
  <%= link_to 'Back', med_histories_path, class: 'waves-effect waves-light btn' %>
  <br>
</div>

app/views/med_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @med_history.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @med_history.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @med_history.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @med_history.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @med_history.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @med_history.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @med_history.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @med_history.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @med_history.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @med_history.q10 %>
</p>

<p>
  <strong>Q11:</strong>
  <%= @med_history.q11 %>
</p>

<p>
  <strong>Q12:</strong>
  <%= @med_history.q12 %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @med_history.patient %>
</p>

<%= link_to 'Edit', edit_med_history_path(@med_history) %> |
<%= link_to 'Back', med_histories_path %>