config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :med_histories
  resources :notes
  resources :events
  resources :recurring_events
  resources :patients do
    resources :med_histories, only: %i[new create]
    resources :notes, only: %i[new create]
  end
  resources :doctors
  get '/chart', to: 'home#chart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :events
  has_many :med_histories
  has_many :notes
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    @user = current_user
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patients = Patient.all
     # MedHistory.all
   end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit; end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to root_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:f_name, :l_name, :gender, :birth_date, :address, :apt_suite, :city, :state, :zip, :phone, :email)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true, :html => {:class => 'row card'}) do |form| %>
<% if patient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(patient.errors.count, "error") %>
      prohibited this patient from being saved:</h2>

    <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card-content">

  <div class="input-field col s6">
    <%= form.label :f_name, 'First Name' %>
    <%= form.text_field :f_name %>
  </div>

  <div class="input-field col s6">
    <%= form.label :l_name, 'Last Name' %>
    <%= form.text_field :l_name %>
  </div>

  <div class="input-field col s6">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="input-field col s6">
    <%# <%= form.label :birth_date, 'Birth Date' %>
      <!-- <%= form.number_field :birth_date %> -->
      <!-- <%= form.date_select :birth_date, class:'datepicker'%> -->

      <%= form.date_field :birth_date, as: :date,label: false, input_html: { class: "datepicker" } %>

    </div>

    <div class="input-field col s6">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="input-field col s6">
      <%= form.label :apt_suite %>
      <%= form.text_field :apt_suite %>
    </div>

    <div class="input-field col s6">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="input-field col s6">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="input-field col s6">
      <%= form.label :zip %>
      <%= form.number_field :zip %>
    </div>

    <div class="input-field col s6">
      <%= form.label :phone %>
      <%= form.number_field :phone %>
    </div>

    <div class="input-field col s6">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="actions">
      <%= form.submit (patient.id ? "Make Changes" : "Add Patient" ), class: 'waves-effect waves-light btn marginbtm' %>
    </div>

  <% end %>

</div>

app/views/patients/_histories.html.erb
<p id="notice"><%= notice %></p>

<% @patient.med_histories.each do |med_history| %>
  <ul class="collapsible">
    <li>
      <div class="collapsible-header">
        <i class="material-icons">filter_drama</i><%= med_history.created_at.strftime('%m/%d/%Y') %></div>
      <div class="collapsible-body">
        <table class="zouttwo">
          <thead>
            <th>Problemas Cardiacos?</th>

            <th>Hepatitis?</th>

            <th>Asma?</th>

            <th>Anemia?</th>

            <th>Embarazada?</th>

            <th>H.I.V?</th>

            <th>Diabetes?</th>

            <th>Presion Sanguinea Anormal</th>

            <th>Asma?</p>

            <th>Epilepsia?</th>

            <th>Esta Tomando Algun Medicamento?</th>

            <th>Transplantado?</th>

          </thead>

          <tbody>

            <tr>
              <span>
                <td><%= med_history.q1 %></td>
                <td><%= med_history.q2 %></td>
                <td><%= med_history.q3 %></td>
                <td><%= med_history.q4 %></td>
                <td><%= med_history.q5 %></td>
                <td><%= med_history.q6 %></td>
                <td><%= med_history.q7 %></td>
                <td><%= med_history.q8 %></td>
                <td><%= med_history.q9 %></td>
                <td><%= med_history.q10 %></td>
                <td><%= med_history.q11 %></td>
                <td><%= med_history.q12 %></td>

              </tr>
            </span>
          </tr>
        </tbody>
      </table>
      <br>
      <%# <td><%= link_to 'Show', med_history %>
        <%# </td>  %>
          <td><%= link_to 'Edit', edit_med_history_path(med_history, @patient) %></td>
          <td><%= link_to 'Delete', med_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      </li>

    </ul>
  <% end %>

  <%=link_to 'new history', new_patient_med_history_path(@patient), class: 'waves-effect waves-light btn'%>

app/views/patients/_notes.html.erb
<h1>Notes</h1>
<div class="card">
  <div class="card-content">
    <table>
      <thead>
        <tr>
          <th>Body</th>
          <th>Patient</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @patient.notes.each do |note| %>
          <tr>
            <td><%= note.body %></td>
            <td><%= "#{note.patient.f_name + " " + note.patient.l_name}"%></td>
            <!-- <td><%= link_to 'Show', note %></td> -->
            <td><%= link_to 'Edit', edit_note_path(note, @patient) %></td>
            <td><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Add Note', new_patient_note_path(@patient), class: 'waves-effect waves-light btn' %>

app/views/patients/edit.html.erb
<div class="container">

  <h1>Patient Record</h1>

  <%= render 'form', patient: @patient %>
</div>
<br>

<div class="container">
  <h1>Medical History</h1>
  <%= render partial: 'histories' %>
</div>
<br>
<div class="container">
  <%= render partial: 'notes' %>
</div>

<%# <%= link_to 'Show', @patient %>
  <%# <%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="card">
    <div class="card-content">
      <h1>Patients</h1>

      <table>
        <thead>
          <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Gender</th>
            <th>Birth_Date</th>
            <th>Adress</th>
            <th>Apt Suite</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone</th>
            <th>Email</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.f_name %></td>
              <td><%= patient.l_name %></td>
              <td><%= patient.gender %></td>
              <td><%= patient.birth_date %></td>
              <td><%= patient.address %></td>
              <td><%= patient.apt_suite %></td>
              <td><%= patient.city %></td>
              <td><%= patient.state %></td>
              <td><%= patient.zip %></td>
              <td><%= patient.phone %></td>
              <td><%= patient.email %></td>
              <%# <td><%= link_to 'Show', patient %>
                <%# </td> %>
                  <td><%= link_to 'Ver', edit_patient_path(patient) %></td>
                  <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>

          <%= link_to 'Add New Patient', new_patient_path, class: 'waves-effect waves-light btn' %>
        </div>

      </div>

    </div>

app/views/patients/new.html.erb
<div class="container">
  <h1>New Patient</h1>

  <%= render 'form', patient: @patient %>
  <%= link_to 'Back', patients_path, class: 'waves-effect waves-light btn-small' %>
</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @patient.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @patient.l_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @patient.birth_date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Apt suite:</strong>
  <%= @patient.apt_suite %>
</p>

<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @patient.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @patient.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %>

<%= link_to 'Back', patients_path %>