config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :med_histories
  resources :notes
  resources :events
  resources :recurring_events
  resources :patients do
    resources :med_histories, only: %i[new create]
    resources :notes, only: %i[new create]
  end
  resources :doctors
  get '/chart', to: 'home#chart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
end

app/models/recurring_event.rb
class RecurringEvent < ApplicationRecord
  enum frequency: { weekly: 0, biweekly: 1, monthly: 2, annually: 3 }

  validates :anchor, presence: true
  validates :frequency, presence: true

  def schedule
    @schedule ||= begin
      schedule = IceCube::Schedule.new(now = anchor)
      case frequency
      when 'weekly'
        schedule.add_recurrence_rule IceCube::Rule.weekly(1)
      when 'biweekly'
        schedule.add_recurrence_rule IceCube::Rule.weekly(2)
      when 'monthly'
        schedule.add_recurrence_rule IceCube::Rule.monthly(1)
      when 'annually'
        schedule.add_recurrence_rule IceCube::Rule.yearly(1)
      end
      schedule
    end
  end

  def events(start_date, end_date)
    start_frequency = start_date ? start_date.to_date : Date.today - 1.year
    end_frequency = end_date ? end_date.to_date : Date.today + 1.year
    schedule.occurrences_between(start_frequency, end_frequency)
  end
end

app/controllers/recurring_events_controller.rb
class RecurringEventsController < ApplicationController
  before_action :set_recurring_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @recurring_events = RecurringEvent.all
    @user = current_user
  end

  def show; end

  def new
    @recurring_event = RecurringEvent.new
  end

  def edit; end

  def create
    @recurring_event = RecurringEvent.new(recurring_event_params)
    @recurring_event.save
  end

  def update
    if params[:event]
      @recurring_event.update(anchor: params[:event][:start])
    else
      @recurring_event.update(recurring_event_params)
    end
  end

  def destroy
    @recurring_event.destroy
  end

  private

  def set_recurring_event
    @recurring_event = RecurringEvent.find(params[:id])
  end

  def recurring_event_params
    params.require(:recurring_event).permit(:title, :anchor, :frequency, :color)
  end
end

app/helpers/recurring_events_helper.rb
module RecurringEventsHelper
end

app/views/recurring_events/_edit.html.erb
<div class="modal fade" id="edit_recurring_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Edit Recurring Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', recurring_event: @recurring_event %>
      </div>
    </div>
  </div>
</div>

app/views/recurring_events/_form.html.erb
<%= simple_form_for @recurring_event, remote: true do |f| %>
<div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :anchor, input_html: { class: "form-control input-sm" } %>
  <%= f.input :frequency, as: :select, collection: RecurringEvent.frequencies.keys, input_html: { class: "form-control input-sm" } %>
  <%= f.input :color, as: :select, collection: [['Black','black'], ['Green','green'], ['Red','red']] %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
  <%= link_to 'New Event', new_event_path, class: 'btn btn-default', remote: true if @recurring_event.new_record? %>
  <%= link_to 'Delete', @recurring_event, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, remote: true unless @recurring_event.new_record? %>
</div>
<% end %>

app/views/recurring_events/_new.html.erb
<div class="modal fade" id="new_recurring_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create New Recurring Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', recurring_event: @recurring_event %>
      </div>
    </div>
  </div>
</div>

app/views/recurring_events/create.js.erb
$('.calendar').fullCalendar( 'renderEvents', $.parseJSON("<%=j render(@recurring_event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/recurring_events/destroy.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_recurring_event').modal('open');

app/views/recurring_events/edit.js.erb
<h1>Editing Recurring Event</h1>

<%= render 'form', recurring_event: @recurring_event %>

<%= link_to 'Show', @recurring_event %> |
<%= link_to 'Back', recurring_events_path %>

app/views/recurring_events/index.js.erb
<p id="notice"><%= notice %></p>

<h1>Recurring Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Anchor</th>
      <th>Frequency</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recurring_events.each do |recurring_event| %>
      <tr>
        <td><%= recurring_event.title %></td>
        <td><%= recurring_event.anchor %></td>
        <td><%= recurring_event.frequency %></td>
        <td><%= recurring_event.color %></td>
        <td><%= link_to 'Show', recurring_event %></td>
        <td><%= link_to 'Edit', edit_recurring_event_path(recurring_event) %></td>
        <td><%= link_to 'Destroy', recurring_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recurring Event', new_recurring_event_path %>

app/views/recurring_events/new.js.erb
$('.modal-backdrop').hide(); $('#remote_container').html('<%= j render "new" %>');
$('#new_recurring_event').modal('open');

app/views/recurring_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recurring_event.title %>
</p>

<p>
  <strong>Anchor:</strong>
  <%= @recurring_event.anchor %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @recurring_event.frequency %>
</p>

<p>
  <strong>Color:</strong>
  <%= @recurring_event.color %>
</p>

<%= link_to 'Edit', edit_recurring_event_path(@recurring_event) %> |
<%= link_to 'Back', recurring_events_path %>

app/views/recurring_events/update.js.erb
$('.calendar').fullCalendar('removeEvents', '<%= "recurring_#{@recurring_event.id}" %>'); $('.calendar').fullCalendar( 'renderEvents', $.parseJSON("<%= j render(@recurring_event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');